COMMON_GROCERY_SEARCHES = (
    "milk",
    "eggs",
    "bread",
    "bananas",
    "chicken breast",
    "apples",
    "cheese",
    "onions",
    "potatoes",
    "butter",
    "tomatoes",
    "ground beef",
    "yogurt",
    "avocados",
    "coffee",
    "cereal",
    "pasta",
    "rice",
    "orange juice",
    "lettuce",
    "frozen pizza",
    "water",
    "snacks",
    "paper towels",
    "toilet paper",
)
